FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

COPY web-automation/pom.xml .
RUN mvn dependency:go-offline -B

COPY web-automation/src ./src

RUN mvn exec:java@playwright-install -B || true

CMD ["mvn", "clean", "test", "-Dtest=SmokeTest"]
