FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

COPY api-automation/pom.xml .
RUN mvn dependency:go-offline -B

COPY api-automation/src ./src

ENV KARATE_ENV=qa
ENV TEST_USER_EMAIL=pruebasQA@gmail.com

CMD ["mvn", "clean", "test", "-Dtest=SmokeRunner"]
